name: CRTP
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - aiohttp=3.8.1
  - aiosignal=1.2.0
  - async-timeout=4.0.1
  - asynctest=0.13.0
  - attrs=21.2.0
  - blas=1.0
  - blinker=1.4
  - blosc=1.21.0
  - brotli=1.0.9
  - brotlipy=0.7.0
  - brunsli=0.1
  - bzip2=1.0.8
  - c-ares=1.17.1
  - ca-certificates=2024.7.2
  - cachetools=4.2.2
  - certifi=2022.12.7
  - cffi=1.14.6
  - cfitsio=3.470
  - charls=2.2.0
  - charset-normalizer=2.0.4
  - click=8.0.3
  - cryptography=3.4.8
  - cudatoolkit=11.3.1
  - cycler=0.11.0
  - cytoolz=0.11.0
  - dask-core=2021.10.0
  - efficientnet-pytorch=0.7.0
  - ffmpeg=4.3
  - fonttools=4.25.0
  - freetype=2.11.0
  - frozenlist=1.2.0
  - future=0.18.2
  - fvcore=0.1.2.post20201122
  - giflib=5.2.1
  - gmp=6.2.1
  - gnutls=3.6.15
  - google-auth=1.33.0
  - google-auth-oauthlib=0.4.4
  - grpcio=1.42.0
  - idna=3.3
  - imagecodecs=2021.8.26
  - imageio=2.9.0
  - intel-openmp=2021.4.0
  - jpeg=9d
  - jxrlib=1.1
  - kiwisolver=1.3.1
  - krb5=1.19.2
  - lame=3.100
  - lcms2=2.12
  - ld_impl_linux-64=2.35.1
  - lerc=3.0
  - libaec=1.0.4
  - libcurl=7.80.0
  - libdeflate=1.8
  - libedit=3.1.20210910
  - libev=4.33
  - libffi=3.3
  - libgcc-ng=9.3.0
  - libgfortran-ng=7.5.0
  - libgfortran4=7.5.0
  - libgomp=9.3.0
  - libiconv=1.15
  - libidn2=2.3.2
  - libnghttp2=1.46.0
  - libpng=1.6.37
  - libprotobuf=3.17.2
  - libssh2=1.9.0
  - libstdcxx-ng=9.3.0
  - libtasn1=4.16.0
  - libtiff=4.2.0
  - libunistring=0.9.10
  - libuv=1.40.0
  - libwebp=1.2.0
  - libwebp-base=1.2.0
  - libzopfli=1.0.3
  - locket=0.2.1
  - lz4-c=1.9.3
  - markdown=3.3.4
  - matplotlib-base=3.5.0
  - mkl=2020.2
  - mkl-service=2.3.0
  - mkl_fft=1.3.0
  - mkl_random=1.1.1
  - multidict=5.1.0
  - munkres=1.1.4
  - ncurses=6.3
  - nettle=3.7.3
  - ninja=1.10.2
  - oauthlib=3.1.1
  - olefile=0.46
  - openh264=2.1.1
  - openjpeg=2.4.0
  - openssl=1.1.1w
  - packaging=21.3
  - partd=1.2.0
  - pillow=8.0.1
  - pip=21.0.1
  - portalocker=2.3.0
  - protobuf=3.17.2
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.8
  - pycparser=2.21
  - pyjwt=2.1.0
  - pyopenssl=21.0.0
  - pyparsing=3.0.4
  - pysocks=1.7.1
  - python=3.7.10
  - python-dateutil=2.8.2
  - python_abi=3.7
  - pytorch=1.10.1
  - pytorch-lightning=1.2.5
  - pytorch-mutex=1.0
  - pywavelets=1.1.1
  - pyyaml=6.0
  - readline=8.1
  - requests=2.26.0
  - requests-oauthlib=1.3.0
  - rsa=4.7.2
  - scikit-image=0.18.1
  - setuptools=49.6.0
  - six=1.16.0
  - snappy=1.1.8
  - sqlite=3.36.0
  - tabulate=0.8.9
  - tensorboard-plugin-wit=1.6.0
  - termcolor=1.1.0
  - tifffile=2021.7.2
  - tk=8.6.11
  - toolz=0.11.2
  - torchvision=0.11.2
  - typing-extensions=3.10.0.2
  - typing_extensions=3.10.0.2
  - ujson=5.1.0
  - urllib3=1.26.7
  - werkzeug=2.0.2
  - wheel=0.37.0
  - xz=5.2.5
  - yacs=0.1.6
  - yaml=0.2.5
  - yarl=1.6.3
  - zfp=0.5.5
  - zipp=3.6.0
  - zlib=1.2.11
  - zstd=1.4.9
  - pip:
      - absl-py==2.1.0
      - albumentations==1.1.0
      - antlr4-python3-runtime==4.8
      - argcomplete==1.12.3
      - argon2-cffi==21.3.0
      - argon2-cffi-bindings==21.2.0
      - astunparse==1.6.3
      - backcall==0.2.0
      - black==21.12b0
      - bleach==4.1.0
      - cached-property==1.5.2
      - carla-birdeye-view==1.1.1
      - cloudpickle==1.3.0
      - cmdstanpy==1.1.0
      - cython==0.29.26
      - dataclasses==0.6
      - datasets==2.13.2
      - debugpy==1.5.1
      - decorator==4.4.2
      - defusedxml==0.7.1
      - descartes==1.1.0
      - dictor==0.1.7
      - dill==0.3.6
      - docker-pycreds==0.4.0
      - einops==0.4.1
      - elementpath==1.3.3
      - entrypoints==0.3
      - ephem==4.1.3
      - filelock==3.0.12
      - filterpy==1.4.5
      - fire==0.4.0
      - flake8==4.0.1
      - flatbuffers==24.3.25
      - fsspec==2023.1.0
      - gast==0.4.0
      - gitdb==4.0.9
      - gitpython==3.1.27
      - google-pasta==0.2.0
      - grad-cam==1.4.8
      - gym==0.17.2
      - h5py==3.6.0
      - holidays==0.27.1
      - huggingface-hub==0.16.4
      - hydra-core==1.1.1
      - imageio-ffmpeg==0.4.5
      - imgaug==0.4.0
      - importlib-metadata==6.7.0
      - importlib-resources==5.4.0
      - iniconfig==1.1.1
      - ipykernel==6.6.0
      - ipython==7.30.1
      - ipython-genutils==0.2.0
      - ipywidgets==7.6.5
      - jedi==0.18.1
      - jinja2==3.0.3
      - joblib==1.1.0
      - jsonschema==4.3.2
      - jupyter==1.0.0
      - jupyter-client==7.1.0
      - jupyter-console==6.4.0
      - jupyter-core==4.9.1
      - jupyterlab-pygments==0.1.2
      - jupyterlab-widgets==1.0.2
      - keras==2.11.0
      - libclang==18.1.1
      - lightgbm==4.6.0
      - llvmlite==0.39.1
      - lmdb==1.3.0
      - markupsafe==2.0.1
      - matplotlib-inline==0.1.3
      - mccabe==0.6.1
      - mistune==0.8.4
      - motmetrics==1.1.3
      - moviepy==1.0.3
      - multiprocess==0.70.14
      - mypy-extensions==0.4.3
      - nbclient==0.5.9
      - nbconvert==6.3.0
      - nbformat==5.1.3
      - nest-asyncio==1.5.4
      - networkx==2.2
      - notebook==6.4.6
      - numba==0.56.4
      - numpy==1.21.6
      - nuscenes-devkit==1.1.0
      - omegaconf==2.1.1
      - online-conformal==1.0.2
      - opencv-python==4.2.0.32
      - opencv-python-headless==4.5.1.48
      - opt-einsum==3.3.0
      - pandas==1.3.5
      - pandocfilters==1.5.0
      - parso==0.8.3
      - pathspec==0.9.0
      - pathtools==0.1.2
      - patsy==1.0.1
      - pexpect==4.8.0
      - pickleshare==0.7.5
      - platformdirs==2.4.1
      - plotly==5.5.0
      - pluggy==1.0.0
      - proglog==0.1.9
      - prometheus-client==0.12.0
      - promise==2.3
      - prompt-toolkit==3.0.24
      - prophet==1.1.7
      - psutil==5.9.0
      - ptyprocess==0.7.0
      - py==1.11.0
      - py-trees==0.8.3
      - py4j==0.10.9.9
      - pyarrow==12.0.1
      - pycocotools==2.0.3
      - pycodestyle==2.8.0
      - pydot==1.4.2
      - pyflakes==2.4.0
      - pygame==2.6.1
      - pyglet==1.5.0
      - pygments==2.10.0
      - pynndescent==0.5.13
      - pyquaternion==0.9.9
      - pyrsistent==0.18.0
      - pytest==6.2.5
      - pytz==2021.3
      - pyzmq==22.3.0
      - qtconsole==5.2.2
      - qtpy==2.0.0
      - qudida==0.0.4
      - salesforce-merlion==2.0.4
      - scikit-learn==1.0.2
      - scipy==1.7.3
      - seaborn==0.12.2
      - send2trash==1.8.0
      - sentry-sdk==1.5.8
      - setproctitle==1.2.2
      - shapely==1.6.4.post2
      - shortuuid==1.0.8
      - smmap==5.0.0
      - stable-baselines3==0.8.0
      - statsmodels==0.13.5
      - tenacity==8.0.1
      - tensorboard==2.11.2
      - tensorboard-data-server==0.6.1
      - tensorflow==2.11.0
      - tensorflow-estimator==2.11.0
      - tensorflow-io-gcs-filesystem==0.34.0
      - terminado==0.12.1
      - testpath==0.5.0
      - threadpoolctl==3.0.0
      - timm==0.5.4
      - toml==0.10.2
      - tomli==1.2.3
      - torchmetrics==0.11.4
      - tornado==6.1
      - tqdm==4.67.1
      - traitlets==5.1.1
      - ttach==0.0.3
      - typed-ast==1.5.1
      - umap==0.1.1
      - umap-learn==0.5.7
      - wandb==0.12.11
      - wcwidth==0.2.5
      - webencodings==0.5.1
      - widgetsnbextension==3.5.2
      - wrapt==1.16.0
      - xmlschema==1.0.18
      - xxhash==3.5.0
      - yaspin==2.1.0
